# Pydantic models for request/response

from pydantic import BaseModel

# Input text provided by user (Request Model)
class ChatbotInput(BaseModel):
    input_text: str

# Output text generated by LLM Chatbot (Response Model)
class ChatbotOutput(BaseModel):
    output_text: str